# configuration for all except 'stable' branch
# Build in Debug
-
  branches:
    except:
    - stable
  version: 0.2.1-{branch}-build{build}
  configuration: Debug
  cache:
    - C:\Users\appveyor\.dnx\packages -> appveyor.yml
  init:
  - ps: >-
      dnvm update-self
  
      dnvm upgrade
  
      dnvm list
  before_build:
  - ps: dnu restore
  - ps: $env:DNX_BUILD_VERSION="$env:APPVEYOR_REPO_BRANCH-build-$env:APPVEYOR_BUILD_NUMBER"
  build:
    verbosity: minimal
  test_script:
  - ps: >-
      foreach ($testdir in (gi tests/*/project.json | Split-Path))
      {
        Push-Location $testdir;
        dnx test;
        Pop-Location;
      }
  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/912155f98bd0aed48efc
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true

# configuration for all except 'stable' branch
# Build in Release, publish to Nuget
-
  branches:
    only:
    - stable
  version: 0.2.1-build{build}
  configuration: Release
  cache:
    - C:\Users\appveyor\.dnx\packages -> appveyor.yml
  init:
  - ps: >-
      dnvm update-self
  
      dnvm upgrade
  
      dnvm list
  before_build:
  - ps: dnu restore
  build:
    verbosity: minimal
  test_script:
  - ps: >-
      foreach ($testdir in (gi tests/*/project.json | Split-Path))
      {
        Push-Location $testdir;
        dnx test;
        Pop-Location;
      }
  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/912155f98bd0aed48efc
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true
  artifacts:
    - path: '**\*.nupkg'
  deploy:
    provider: NuGet
    api_key:
      secure: Qiw6Qq0ZTIhBoy4L1QT3whagCQAKK6/KcjxDz6XhzHuTnmLr4sdPtRvx2AHc5zGp
    skip_symbols: false
    artifact: /.*\.nupkg/
