image: Visual Studio 2017
version: 0.5-alpha.build{build}
skip_tags: true
configuration:
  - Debug
  - Release
cache:
  - '%USERPROFILE%\.nuget\packages'
init:
# checking if release branch
  - ps: |
      # set release_branch
      $env:release_branch = $env:APPVEYOR_REPO_BRANCH.StartsWith("release")
      echo "release_branch='$env:release_branch'"
# get .NET Core SDK v2.1 if not available
  - ps: |
      if ([System.Version](dotnet --version) -ge [System.Version]"2.1.300") {
        $scriptPath = 'C:\dotnet-install.ps1'
        (New-Object System.Net.WebClient).DownloadString('https://dot.net/v1/dotnet-install.ps1', $scriptPath)
        iex '$scriptPath --channel 2.1.300'
      }
  - ps: dotnet --info
before_build:
# set build version
  - ps: |
      $versionjson = ((Get-Content 'src/version.json') | ConvertFrom-Json).version
      Update-AppveyorBuild -Version "$versionjson.build$env:APPVEYOR_BUILD_NUMBER"
build_script:
  - msbuild /v:m /t:Restore,Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/ed65900fc71d1cd43a2e
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/warhub/api/v2/package
    symbol_server: https://www.myget.org/F/warhub/symbols/api/v2/package
    api_key:
      secure: zir2+Fju3dWWwtAJzFuDJdCZC328XUVdSq1eyBVHFcdGvSzHvnzOI7ljkRy9Z1AI
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      configuration: Debug
      release_branch: false
  - provider: NuGet
    api_key:
      secure: fZIteIAxcxCICf9XQzv6dY3E1CUyErebh6Um+mzb7v3vXvvTAbHxgTyYr7srzO/i
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      configuration: Release
      release_branch: true
