# configuration for all except 'stable' branch
# Build in Debug
-
  branches:
    except:
    - stable
  version: 0.2.2-{branch}-build{build}
  configuration: Debug
  cache:
    - C:\Users\appveyor\.nuget\packages -> appveyor.yml
  init:
  - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
  - cmd: dotnet-dev-win-x64.latest.exe /quiet
  - ps: dotnet --info
  environment:
    PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  before_build:
  - ps: dotnet restore
  - ps: $env:DOTNET_BUILD_VERSION="$env:APPVEYOR_REPO_BRANCH-build-$env:APPVEYOR_BUILD_NUMBER"
  build:
    verbosity: minimal
  test_script:
  - ps: >-
      foreach ($testdir in (gi tests/*/project.json | Split-Path))
      {
        Push-Location $testdir;
        dotnet test;
        Pop-Location;
      }
  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/912155f98bd0aed48efc
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true

# configuration for all except 'stable' branch
# Build in Release, publish to Nuget
-
  branches:
    only:
    - stable
  version: 0.2.2-build{build}
  configuration: Release
  cache:
    - C:\Users\appveyor\.nuget\packages -> appveyor.yml
  init:
  - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
  - cmd: dotnet-dev-win-x64.latest.exe /quiet
  - ps: dotnet --info
  environment:
    PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  before_build:
  - ps: dotnet restore
  build:
    verbosity: minimal
  after_build:
  - ps: >-
      foreach($srcdir in (gi src/*/project.json | Split-Path))
      {
        Push-Location $srcdir;
        dotnet pack;
        Pop-Location;
      }
  test_script:
  - ps: >-
      foreach ($testdir in (gi tests/*/project.json | Split-Path))
      {
        Push-Location $testdir;
        dotnet test;
        Pop-Location;
      }
  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/912155f98bd0aed48efc
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true
  artifacts:
    - path: '**\*.nupkg'
  deploy:
    provider: NuGet
    api_key:
      secure: Qiw6Qq0ZTIhBoy4L1QT3whagCQAKK6/KcjxDz6XhzHuTnmLr4sdPtRvx2AHc5zGp
    skip_symbols: false
    artifact: /.*\.nupkg/
